import Fastify from 'fastify'
import cors from '@fastify/cors'
import { FetchHttpTransport } from './adapters/http-transport.js'
import { McsmHttpAdapter } from './adapters/mcsm-http-adapter.js'
import type { McsmAdapter, McsmInstance } from './adapters/mcsm-adapter.js'

export type DemoInstance = { id: string; name: string; lifecycle: 'RUNNING' | 'STOPPED' | 'STARTING' | 'STOPPING' | 'ABNORMAL'; health: 'LOCAL_READY' | 'UNVERIFIED' | 'PREPARING' | 'UNAVAILABLE'; gameVersion: string; serverCore: string; loginMode: 'OFFLINE' | 'ONLINE' | 'UNKNOWN'; workDirectory: string; port: number; players: { online: number; max: number; source: string }; observedAt: string }
export type DemoTask = { taskId: string; kind: string; state: string; actorId: string; idempotencyKey: string; resourceId?: string; currentStep?: string; progress: { completed: number; total: number }; createdAt: string; updatedAt: string; message?: string }

const now = () => new Date().toISOString()
const instances: DemoInstance[] = [
  { id: 'demo-paper-001', name: '纸片生存服', lifecycle: 'RUNNING', health: 'LOCAL_READY', gameVersion: '1.20.1', serverCore: 'PAPER', loginMode: 'OFFLINE', workDirectory: '/home/mc-agent/workspaces/paper-001', port: 25565, players: { online: 2, max: 12, source: 'Demo' }, observedAt: now() },
  { id: 'demo-vanilla-002', name: '原版建造服', lifecycle: 'STOPPED', health: 'UNVERIFIED', gameVersion: '1.21.1', serverCore: 'VANILLA', loginMode: 'ONLINE', workDirectory: '/home/mc-agent/workspaces/vanilla-002', port: 25566, players: { online: 0, max: 8, source: 'Demo' }, observedAt: now() },
  { id: 'demo-forge-003', name: 'Forge 测试服', lifecycle: 'ABNORMAL', health: 'UNAVAILABLE', gameVersion: '1.20.1', serverCore: 'FORGE', loginMode: 'OFFLINE', workDirectory: '/home/mc-agent/workspaces/forge-003', port: 25567, players: { online: 0, max: 10, source: 'Demo' }, observedAt: now() },
]
const tasks = new Map<string, DemoTask>()
const auditEvents: Array<{ eventId: string; taskId: string; actorId: string; type: string; summary: string; occurredAt: string }> = []
const idempotentTasks = new Map<string, DemoTask>()
const record = (taskId: string, type: string, summary: string) => auditEvents.unshift({ eventId: `${taskId}-${auditEvents.length + 1}`, taskId, actorId: 'demo-admin', type, summary, occurredAt: now() })

const idempotencyKeyPattern = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/
const isValidIdempotencyKey = (value: unknown): value is string => typeof value === 'string' && idempotencyKeyPattern.test(value)
const invalidRequest = (reply: { code: (statusCode: number) => { send: (payload: unknown) => unknown } }, message: string) => reply.code(400).send({ code: 'INVALID_REQUEST', message, retryable: false, requiresReconciliation: false })
const idempotent = (scope: string, key: string, create: () => DemoTask): { task: DemoTask; replay: boolean } => {
  const compoundKey = `${scope}:${key}`
  const existing = idempotentTasks.get(compoundKey)
  if (existing) return { task: existing, replay: true }
  const task = create()
  idempotentTasks.set(compoundKey, task)
  return { task, replay: false }
}

const realConfig = process.env.MCSM_BASE_URL && process.env.MCSM_DAEMON_ID && process.env.MCSM_TOKEN && process.env.MCSM_COOKIE
const mcsm: McsmAdapter | undefined = realConfig ? new McsmHttpAdapter(new FetchHttpTransport(process.env.MCSM_BASE_URL!, { token: process.env.MCSM_TOKEN!, headers: { cookie: process.env.MCSM_COOKIE! } }), process.env.MCSM_DAEMON_ID!) : undefined
const mode = mcsm ? 'real' : 'demo'

const statusMap: Record<McsmInstance['state'], DemoInstance['lifecycle']> = { running: 'RUNNING', stopped: 'STOPPED', starting: 'STARTING', stopping: 'STOPPING', unknown: 'ABNORMAL' }
function productInstance(instance: McsmInstance): DemoInstance { return { id: instance.id, name: instance.name, lifecycle: statusMap[instance.state], health: instance.state === 'running' ? 'UNVERIFIED' : 'UNAVAILABLE', gameVersion: 'UNKNOWN', serverCore: 'UNKNOWN', loginMode: 'UNKNOWN', workDirectory: instance.workDirectory, port: instance.port ?? 0, players: { online: 0, max: 0, source: 'MCSManager 未提供游戏人数' }, observedAt: now() } }
async function listInstances(): Promise<DemoInstance[]> { return mcsm ? (await mcsm.listInstances()).map(productInstance) : [...instances] }

function scheduleDemoControl(instance: DemoInstance, action: 'START' | 'STOP' | 'RESTART', idempotencyKey: string): DemoTask { const taskId = `task-${idempotencyKey}`; const existing = tasks.get(taskId); if (existing) return existing; const task: DemoTask = { taskId, kind: 'CONTROL', state: 'EXECUTING', actorId: 'demo-admin', idempotencyKey, resourceId: instance.id, currentStep: '正在读取实际状态', progress: { completed: 1, total: action === 'RESTART' ? 4 : 3 }, createdAt: now(), updatedAt: now() }; tasks.set(taskId, task); record(taskId, 'REQUESTED', `${action} ${instance.name}`); setTimeout(() => { instance.lifecycle = action === 'START' ? 'STARTING' : 'STOPPING'; instance.health = 'PREPARING'; instance.observedAt = now(); task.currentStep = action === 'RESTART' ? '正在正常停止实例' : `正在${action === 'START' ? '启动' : '停止'}实例`; task.progress.completed = 2; task.updatedAt = now() }, 160); setTimeout(() => { instance.lifecycle = action === 'STOP' ? 'STOPPED' : 'RUNNING'; instance.health = action === 'STOP' ? 'UNVERIFIED' : 'LOCAL_READY'; instance.players.online = action === 'STOP' ? 0 : instance.players.online; instance.observedAt = now(); task.currentStep = '正在确认服务状态'; task.progress.completed = task.progress.total - 1; task.updatedAt = now() }, 420); setTimeout(() => { task.state = 'SUCCEEDED'; task.currentStep = '已通过事实验证'; task.progress.completed = task.progress.total; task.updatedAt = now(); record(taskId, 'VERIFICATION', `${instance.name} ${task.state}`) }, 700); return task }

async function waitForRealState(instanceId: string, expected: 'running' | 'stopped', maxChecks = 120): Promise<McsmInstance | undefined> { for (let attempt = 0; attempt < maxChecks; attempt += 1) { const observed = await mcsm!.getInstance(instanceId); if (observed?.state === expected) return observed; await new Promise((resolve) => setTimeout(resolve, 250)) } return await mcsm!.getInstance(instanceId) }
async function scheduleRealControl(instance: McsmInstance, action: 'START' | 'STOP' | 'RESTART', idempotencyKey: string): Promise<DemoTask> { const taskId = `task-${idempotencyKey}`; const existing = tasks.get(taskId); if (existing) return existing; const task: DemoTask = { taskId, kind: 'CONTROL', state: 'EXECUTING', actorId: 'demo-admin', idempotencyKey, resourceId: instance.id, currentStep: '正在调用 MCSManager', progress: { completed: 1, total: action === 'RESTART' ? 4 : 3 }, createdAt: now(), updatedAt: now() }; tasks.set(taskId, task); record(taskId, 'REQUESTED', `${action} ${instance.name}`); try { if (action === 'STOP') await mcsm!.stopInstance(instance.id, idempotencyKey); else if (action === 'START') await mcsm!.startInstance(instance.id, idempotencyKey); else { await mcsm!.stopInstance(instance.id, `${idempotencyKey}:stop`); task.currentStep = '正在等待实例停止'; task.progress.completed = 2; await waitForRealState(instance.id, 'stopped'); task.currentStep = '正在重新启动实例'; await mcsm!.startInstance(instance.id, `${idempotencyKey}:start`) } task.currentStep = '正在观察目标状态'; task.progress.completed = task.progress.total - 1; const expected = action === 'STOP' ? 'stopped' : 'running'; const observed = await waitForRealState(instance.id, expected); task.state = observed?.state === expected ? 'SUCCEEDED' : 'PARTIAL'; task.currentStep = task.state === 'SUCCEEDED' ? '已读取 MCSManager 状态' : 'MCSManager 状态尚未达到目标'; task.progress.completed = task.progress.total; task.updatedAt = now(); record(taskId, 'VERIFICATION', `${action} ${task.state}`) } catch (error) { task.state = 'FAILED'; task.currentStep = 'MCSManager 操作失败'; task.message = error instanceof Error ? error.message : String(error); task.progress.completed = task.progress.total; task.updatedAt = now(); record(taskId, 'BLOCKED', task.message) } return task }

const app = Fastify({ logger: process.env.NODE_ENV !== 'test' })
await app.register(cors, { origin: true, credentials: true })
app.get('/healthz', async () => ({ ok: true, service: 'mc-ai-manager-api', mode }))
app.get('/api/v1/agent/status', async (_request, reply) => { try { const response = await fetch(process.env.DSH_BASE_URL ?? 'http://127.0.0.1:3080'); return { reachable: response.ok, status: response.status, service: 'DeepSeek Harness GUI', integration: '当前未配置通用 Agent REST 调用协议' } } catch { return reply.code(503).send({ reachable: false, code: 'AGENT_UNAVAILABLE', message: '无法连接 DeepSeek Harness', retryable: true, requiresReconciliation: false }) } })
app.get('/api/v1/auth/session', async () => ({ userId: 'demo-admin', role: 'DEPLOY_ADMIN', expiresAt: new Date(Date.now() + 3_600_000).toISOString(), mode }))
app.get('/api/v1/instances', async (_request, reply) => { try { return { items: await listInstances(), observedAt: now(), source: mode === 'real' ? 'MCSManager' : 'Demo' } } catch (error) { return reply.code(502).send({ code: 'MCSMANAGER_UNAVAILABLE', message: error instanceof Error ? error.message : String(error), retryable: false, requiresReconciliation: true }) } })
app.get<{ Params: { instanceId: string } }>('/api/v1/instances/:instanceId', async (request, reply) => { const item = (await listInstances()).find((x) => x.id === request.params.instanceId); return item ?? reply.code(404).send({ code: 'NOT_FOUND', message: '实例不存在', retryable: false, requiresReconciliation: false }) })
app.get('/api/v1/tasks/latest', async () => { const latest = [...tasks.values()].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))[0]; return latest ?? { taskId: null, state: 'IDLE', progress: { completed: 0, total: 0 }, message: '当前没有任务' } })
app.get<{ Params: { taskId: string } }>('/api/v1/tasks/:taskId', async (request, reply) => { const task = tasks.get(request.params.taskId); return task ?? reply.code(404).send({ code: 'NOT_FOUND', message: '任务不存在', retryable: false, requiresReconciliation: false }) })
app.post<{ Params: { instanceId: string }; Body: { action: 'START' | 'STOP' | 'RESTART'; idempotencyKey: string } }>('/api/v1/instances/:instanceId/actions', async (request, reply) => { const body = request.body; if (!body || typeof body !== 'object' || !isValidIdempotencyKey(body.idempotencyKey) || !['START', 'STOP', 'RESTART'].includes(body.action)) return invalidRequest(reply, 'action 必须为 START、STOP 或 RESTART，且 idempotencyKey 必须为 1-128 位安全字符'); const item = mcsm ? await mcsm.getInstance(request.params.instanceId) : instances.find((x) => x.id === request.params.instanceId); if (!item) return reply.code(404).send({ code: 'NOT_FOUND', message: '实例不存在' }); const key = `control:${request.params.instanceId}:${body.idempotencyKey}`; const existing = idempotentTasks.get(key); if (existing) { if (existing.resourceId !== request.params.instanceId) return reply.code(409).send({ code: 'IDEMPOTENCY_CONFLICT', message: '幂等键已绑定其他资源', retryable: false, requiresReconciliation: false }); return reply.code(202).send({ taskId: existing.taskId, state: existing.state }) } const task = mcsm ? await scheduleRealControl(item as McsmInstance, body.action, body.idempotencyKey) : scheduleDemoControl(item as DemoInstance, body.action, body.idempotencyKey); idempotentTasks.set(key, task); return reply.code(202).send({ taskId: task.taskId, state: task.state }) })
app.post<{ Body: { name: string; loginMode: 'OFFLINE' | 'ONLINE'; eulaAccepted: boolean; idempotencyKey: string } }>('/api/v1/deployments/demo', async (request, reply) => { const body = request.body; if (!body || typeof body !== 'object' || typeof body.name !== 'string' || body.name.trim().length < 1 || body.name.length > 80 || !['OFFLINE', 'ONLINE'].includes(body.loginMode) || typeof body.eulaAccepted !== 'boolean' || !isValidIdempotencyKey(body.idempotencyKey)) return invalidRequest(reply, 'name、loginMode、eulaAccepted 和 idempotencyKey 参数无效'); if (!body.eulaAccepted) return reply.code(409).send({ code: 'EULA_REQUIRED', message: '需要确认 Minecraft EULA', retryable: false, requiresReconciliation: false }); const result = idempotent(`deployment:${body.idempotencyKey}`, body.idempotencyKey, () => { const taskId = `task-deploy-${body.idempotencyKey}`; const task: DemoTask = { taskId, kind: 'DEPLOY', state: 'EXECUTING', actorId: 'demo-admin', idempotencyKey: body.idempotencyKey, currentStep: '正在识别服务端并检查空间', progress: { completed: 1, total: 5 }, createdAt: now(), updatedAt: now(), message: 'Demo 演示任务；未写入真实文件' }; tasks.set(taskId, task); record(taskId, 'REQUESTED', `部署 ${body.name}`); setTimeout(() => { task.currentStep = '正在创建 Demo 实例'; task.progress.completed = 2; task.updatedAt = now() }, 200); setTimeout(() => { task.currentStep = '正在模拟启动并读取服务状态'; task.progress.completed = 3; task.updatedAt = now() }, 500); setTimeout(() => { const id = `demo-upload-${body.idempotencyKey.slice(-6)}`; instances.unshift({ id, name: body.name, lifecycle: 'RUNNING', health: 'LOCAL_READY', gameVersion: '1.20.1', serverCore: 'PAPER', loginMode: body.loginMode, workDirectory: `/home/mc-agent/workspaces/${id}`, port: 25568, players: { online: 0, max: 12, source: 'Demo' }, observedAt: now() }); task.currentStep = '已通过 Demo 事实验证'; task.progress.completed = 5; task.state = 'SUCCEEDED'; task.updatedAt = now(); record(taskId, 'VERIFICATION', `部署 ${task.state}`) }, 900); return task }); return reply.code(202).send({ taskId: result.task.taskId, state: result.task.state }) })
app.get('/api/v1/audit-events', async () => ({ items: auditEvents }))

const port = Number(process.env.MC_AI_MANAGER_PORT ?? 8787)
if (process.env.NODE_ENV !== 'test') await app.listen({ host: '127.0.0.1', port })
export { app, instances, tasks, mode }
